interface SurahTranslations {
    [key: string]: string;
}

export const surahTranslations : SurahTranslations = {
    "Al-Faatiha": "L'Ouverture",
    "Al-Baqara": "La Vache",
    "Aal-i-Imraan": "La Famille d'Imran",
    "An-Nisaa": "Les Femmes",
    "Al-Maaida": "La Table Servie",
    "Al-An'aam": "Les Bestiaux",
    "Al-A'raaf": "Les Murailles",
    "Al-Anfaal": "Le Butin",
    "At-Tawba": "Le Repentir",
    "Yunus": "Jonas",
    "Hud": "Hud",
    "Yusuf": "Joseph",
    "Ar-Ra'd": "Le Tonnerre",
    "Ibrahim": "Abraham",
    "Al-Hijr": "Al-Hijr",
    "An-Nahl": "Les Abeilles",
    "Al-Israa": "Le Voyage Nocturne",
    "Al-Kahf": "La Caverne",
    "Maryam": "Marie",
    "Taa-Haa": "Ta-Ha",
    "Al-Anbiyaa": "Les Prophètes",
    "Al-Hajj": "Le Pèlerinage",
    "Al-Muminoon": "Les Croyants",
    "An-Noor": "La Lumière",
    "Al-Furqaan": "Le Discernement",
    "Ash-Shu'araa": "Les Poètes",
    "An-Naml": "Les Fourmis",
    "Al-Qasas": "Le Récit",
    "Al-Ankaboot": "L'Araignée",
    "Ar-Room": "Les Romains",
    "Luqman": "Luqman",
    "As-Sajda": "La Prosternation",
    "Al-Ahzaab": "Les Coalisés",
    "Saba": "Saba",
    "Faatir": "Le Créateur",
    "Yaseen": "Ya-Sin",
    "As-Saaffaat": "Les Rangés",
    "Saad": "Sad",
    "Az-Zumar": "Les Groupes",
    "Ghafir": "Le Pardonneur",
    "Fussilat": "Les Versets Détaillés",
    "Ash-Shura": "La Consultation",
    "Az-Zukhruf": "L'Ornement",
    "Ad-Dukhaan": "La Fumée",
    "Al-Jaathiya": "L'Agenouillée",
    "Al-Ahqaf": "Al-Ahqaf",
    "Muhammad": "Muhammad",
    "Al-Fath": "La Victoire",
    "Al-Hujuraat": "Les Appartements",
    "Qaaf": "Qaf",
    "Adh-Dhaariyat": "Qui Éparpillent",
    "At-Tur": "Le Mont",
    "An-Najm": "L'Étoile",
    "Al-Qamar": "La Lune",
    "Ar-Rahmaan": "Le Tout Miséricordieux",
    "Al-Waaqia": "L'Événement",
    "Al-Hadid": "Le Fer",
    "Al-Mujaadila": "La Discussion",
    "Al-Hashr": "L'Exode",
    "Al-Mumtahana": "L'Éprouvée",
    "As-Saff": "Le Rang",
    "Al-Jumu'a": "Le Vendredi",
    "Al-Munaafiqoon": "Les Hypocrites",
    "At-Taghaabun": "La Grande Perte",
    "At-Talaaq": "Le Divorce",
    "At-Tahrim": "L'Interdiction",
    "Al-Mulk": "La Royauté",
    "Al-Qalam": "La Plume",
    "Al-Haaqqa": "L'Inévitable",
    "Al-Ma'aarij": "Les Voies d'Ascension",
    "Nooh": "Noé",
    "Al-Jinn": "Les Djinns",
    "Al-Muzzammil": "L'Enveloppé",
    "Al-Muddaththir": "Le Revêtu d'un Manteau",
    "Al-Qiyaama": "La Résurrection",
    "Al-Insaan": "L'Homme",
    "Al-Mursalaat": "Les Envoyés",
    "An-Naba": "La Nouvelle",
    "An-Naazi'aat": "Les Anges qui Arrachent",
    "Abasa": "Il s'est Renfrogné",
    "At-Takwir": "L'Obscurcissement",
    "Al-Infitaar": "La Rupture",
    "Al-Mutaffifin": "Les Fraudeurs",
    "Al-Inshiqaaq": "La Déchirure",
    "Al-Burooj": "Les Constellations",
    "At-Taariq": "L'Astre Nocturne",
    "Al-A'laa": "Le Très-Haut",
    "Al-Ghaashiya": "L'Enveloppante",
    "Al-Fajr": "L'Aube",
    "Al-Balad": "La Cité",
    "Ash-Shams": "Le Soleil",
    "Al-Lail": "La Nuit",
    "Ad-Dhuhaa": "Le Jour Montant",
    "Ash-Sharh": "L'Ouverture",
    "At-Tin": "Le Figuier",
    "Al-Alaq": "L'Adhérence",
    "Al-Qadr": "La Destinée",
    "Al-Bayyina": "La Preuve",
    "Az-Zalzala": "La Secousse",
    "Al-Aadiyaat": "Les Coursiers",
    "Al-Qaari'a": "Le Fracas",
    "At-Takaathur": "La Course aux Richesses",
    "Al-Asr": "Le Temps",
    "Al-Humaza": "Les Calomniateurs",
    "Al-Fil": "L'Éléphant",
    "Quraish": "Les Quraysh",
    "Al-Maa'un": "L'Ustensile",
    "Al-Kawthar": "L'Abondance",
    "Al-Kaafiroon": "Les Infidèles",
    "An-Nasr": "Les Secours",
    "Al-Masad": "Les Fibres",
    "Al-Ikhlaas": "Le Monothéisme Pur",
    "Al-Falaq": "L'Aube Naissante",
    "An-Naas": "Les Hommes"
};