export const FETCH_SOURATES_REQUEST = 'FETCH_SOURATES_REQUEST';
export const FETCH_SOURATES_SUCCESS = 'FETCH_SOURATES_SUCCESS';
export const FETCH_SOURATES_FAILURE = 'FETCH_SOURATES_FAILURE';

export const FETCH_VERSES_REQUEST = 'FETCH_VERSES_REQUEST';
export const FETCH_VERSES_SUCCESS = 'FETCH_VERSES_SUCCESS';
export const FETCH_VERSES_FAILURE = 'FETCH_VERSES_FAILURE';
