export const FETCH_SOURATES_REQUEST = "FETCH_SOURATES_REQUEST";
export const FETCH_SOURATES_SUCCESS = "FETCH_SOURATES_SUCCESS";
export const FETCH_SOURATES_FAILURE = "FETCH_SOURATES_FAILURE";

export const FETCH_VERSES_REQUEST = "FETCH_VERSES_REQUEST";
export const FETCH_VERSES_SUCCESS = "FETCH_VERSES_SUCCESS";
export const FETCH_VERSES_FAILURE = "FETCH_VERSES_FAILURE";

export const FETCH_DATE_REQUEST = "FETCH_DATE_REQUEST";
export const FETCH_DATE_SUCCESS = "FETCH_DATE_SUCCESS";
export const FETCH_DATE_FAILURE = "FETCH_DATE_FAILURE";

export const FETCH_PRAYERS_REQUEST = "FETCH_PRAYERS_REQUEST";
export const FETCH_PRAYERS_SUCCESS = "FETCH_PRAYERS_SUCCESS";
export const FETCH_PRAYERS_FAILURE = "FETCH_PRAYERS_FAILURE";

export const FETCH_NEXT_PRAYER_REQUEST = "FETCH_NEXT_PRAYER_REQUEST";
export const FETCH_NEXT_PRAYER_SUCCESS = "FETCH_NEXT_PRAYER_SUCCESS";
export const FETCH_NEXT_PRAYER_FAILURE = "FETCH_NEXT_PRAYER_FAILURE";
